server:
  port: 8081

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<rest>.*),/auth/${rest}
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<rest>.*),/users/${rest}
        - id: car-service
          uri: http://localhost:8083
          predicates:
            - Path=/cars/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: DEBUG
    org.springframework.cloud.gateway.filter.NettyRoutingFilter: DEBUG
  pattern:
    console: "%d{HH:mm:ss} [%X{requestId}] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info

jwt:
  secret: "VkqW3Us7zRA2TxmjLzvD6qShEXAMPLEKEYDUMMYtJwRMqYkzXoDcs1pB"
