server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**
          filters:
            - name: RewritePath
              args:
                regexp: '/users/(?<rest>.*)'
                replacement: '/users/${rest}'

        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/orders/**
          filters:
            - name: StripPrefix
              args:
                parts: 1

logging:
  level:
    com.example.apigateway.filter: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{requestId}] %-5level %logger{36} - %msg%n"

jwt:
  secret: "VkqW3Us7zRA2TxmjLzvD6qShEXAMPLEKEYDUMMYtJwRMqYkzXoDcs1pB"
