server:
  port: 8081

spring:
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<rest>.*),/users/${rest}

logging:
  level:
    org.springframework.cloud.gateway: TRACE
